const QUESTIONS = [
// ── MULTIPLE CHOICE ──────────────────────────────────────────────────────────
{id:"mc_001",type:"mc",topic:"present_perfect_vs_past_simple",
question:"I _____ my passport. Have you seen it anywhere?",
options:["lost","have lost","was losing","had lost"],
answer:"have lost",alternates:[],
hint:"Use present perfect when the action has a result in the present (the passport is still missing now)."},

{id:"mc_002",type:"mc",topic:"past_continuous",
question:"When I arrived at the party, everyone _____ and laughing.",
options:["danced","was dancing","has danced","had danced"],
answer:"was dancing",alternates:[],
hint:"Use past continuous for an action already in progress when another (past simple) action occurred."},

{id:"mc_003",type:"mc",topic:"conditionals",
question:"If I _____ more time, I would learn another language.",
options:["have","had","will have","would have"],
answer:"had",alternates:[],
hint:"Conditional type 2: 'If + past simple, would + bare infinitive'. Never use 'would' in the if-clause."},

{id:"mc_004",type:"mc",topic:"modal_verbs",
question:"You _____ make so much noise — people are trying to sleep.",
options:["don't have to","mustn't","shouldn't have","needn't"],
answer:"mustn't",alternates:[],
hint:"'Mustn't' = prohibition (not allowed). 'Don't have to' = not necessary. These are very different meanings."},

{id:"mc_005",type:"mc",topic:"articles",
question:"She works as _____ architect for _____ large firm in the city.",
options:["an / a","a / the","an / the","the / a"],
answer:"an / a",alternates:[],
hint:"Use 'an' before vowel sounds ('architect'). Use 'a' for first mention of a singular countable noun."},

{id:"mc_006",type:"mc",topic:"verb_patterns_gerund",
question:"She couldn't help _____ when she heard the news.",
options:["to cry","cry","crying","cried"],
answer:"crying",alternates:[],
hint:"'Can't help' is always followed by a gerund (-ing). You cannot 'can't help to do' something."},

{id:"mc_007",type:"mc",topic:"passive",
question:"The new bridge _____ by the end of next year.",
options:["will complete","will be completed","is completing","completes"],
answer:"will be completed",alternates:[],
hint:"Future passive: 'will be + past participle'. The bridge is the object of completing, not the subject."},

{id:"mc_008",type:"mc",topic:"reported_speech",
question:"She said she _____ tired and wanted to go home.",
options:["is","was","has been","would be"],
answer:"was",alternates:[],
hint:"In reported speech, present simple ('is') shifts one tense back to past simple ('was')."},

{id:"mc_009",type:"mc",topic:"quantifiers",
question:"There isn't _____ information available on this topic.",
options:["many","few","much","little"],
answer:"much",alternates:[],
hint:"'Information' is uncountable. Use 'much' (not 'many') with uncountable nouns in negatives/questions."},

{id:"mc_010",type:"mc",topic:"adjectives_ed_ing",
question:"The lecture was so _____ that half the audience fell asleep.",
options:["bored","boring","boredom","boringly"],
answer:"boring",alternates:[],
hint:"'-ing' adjectives describe a quality of the thing itself (the lecture causes boredom). '-ed' describes how a person feels."},

{id:"mc_011",type:"mc",topic:"comparative_superlative",
question:"This is _____ coffee I've ever tasted.",
options:["the worse","the worst","the most bad","worse"],
answer:"the worst",alternates:[],
hint:"'Worst' is the irregular superlative of 'bad'. Always use 'the' before superlatives."},

{id:"mc_012",type:"mc",topic:"relative_clauses",
question:"The colleague _____ desk is next to mine has just resigned.",
options:["who","which","whose","that"],
answer:"whose",alternates:[],
hint:"'Whose' shows possession in relative clauses. It replaces a possessive like 'his/her/their'."},

{id:"mc_013",type:"mc",topic:"past_perfect",
question:"By the time the ambulance arrived, the patient _____ consciousness.",
options:["lost","has lost","had lost","was losing"],
answer:"had lost",alternates:[],
hint:"Use past perfect ('had + past participle') for an action completed before another past action."},

{id:"mc_014",type:"mc",topic:"future_forms",
question:"Look at those dark clouds. It _____ rain any minute now.",
options:["will","is going to","is about to","shall"],
answer:"is going to",alternates:[],
hint:"Use 'going to' for predictions based on present visible evidence (the dark clouds)."},

{id:"mc_015",type:"mc",topic:"tag_questions",
question:"Nobody called while I was out, _____?",
options:["didn't they","did they","weren't they","were they"],
answer:"did they",alternates:[],
hint:"'Nobody' is negative, so the tag is positive. The auxiliary matches the tense: 'did'."},

{id:"mc_016",type:"mc",topic:"state_verbs",
question:"I _____ what you're trying to say, but I disagree completely.",
options:["am understanding","understand","have understood","was understanding"],
answer:"understand",alternates:[],
hint:"'Understand' is a state verb — it describes a mental state, not an action, so it is not used in continuous tenses."},

{id:"mc_017",type:"mc",topic:"conditionals",
question:"If we _____ left earlier, we wouldn't have missed the train.",
options:["had","would have","have","could have"],
answer:"had",alternates:[],
hint:"Conditional type 3: 'If + past perfect, would have + past participle'. The if-clause never takes 'would'."},

{id:"mc_018",type:"mc",topic:"passive",
question:"The contract _____ before we can proceed with the project.",
options:["must sign","must be signed","must have signed","must be signing"],
answer:"must be signed",alternates:[],
hint:"Modal passive: 'modal + be + past participle'. The contract cannot sign itself."},

{id:"mc_019",type:"mc",topic:"present_perfect_continuous",
question:"She _____ for this company for over fifteen years.",
options:["works","has worked","has been working","worked"],
answer:"has been working",alternates:[],
hint:"Present perfect continuous emphasises the ongoing, uninterrupted nature of an action continuing to the present."},

{id:"mc_020",type:"mc",topic:"verb_patterns_gerund_infinitive",
question:"I remember _____ her at the conference two years ago.",
options:["to meet","meeting","meet","to have met"],
answer:"meeting",alternates:[],
hint:"'Remember + gerund' = recall a past event. 'Remember + infinitive' = not forget to do something in the future."},

{id:"mc_021",type:"mc",topic:"prepositions_time",
question:"The meeting has been rescheduled _____ Friday _____ 3 p.m.",
options:["on / at","in / at","at / on","on / in"],
answer:"on / at",alternates:[],
hint:"Use 'on' with days of the week; use 'at' with specific clock times."},

{id:"mc_022",type:"mc",topic:"adverbs_vs_adjectives",
question:"He speaks English _____ , even though he only started learning two years ago.",
options:["fluent","more fluent","fluently","most fluently"],
answer:"fluently",alternates:[],
hint:"Adverbs modify verbs ('speaks'). 'Fluently' is the adverb form of the adjective 'fluent'."},

{id:"mc_023",type:"mc",topic:"countable_uncountable",
question:"Could you give me _____ advice on how to improve my writing?",
options:["an","a few","some","many"],
answer:"some",alternates:[],
hint:"'Advice' is uncountable — it has no plural form and cannot take 'a/an'. Use 'some' or 'a piece of'."},

{id:"mc_024",type:"mc",topic:"conjunctions",
question:"She studied hard _____ she was completely exhausted.",
options:["despite","however","even though","in spite"],
answer:"even though",alternates:[],
hint:"'Even though' introduces a contrast clause. 'Despite' and 'in spite of' are followed by a noun or gerund, not a clause."},

{id:"mc_025",type:"mc",topic:"modal_verbs",
question:"You _____ have told me about the change — I wasted an entire afternoon.",
options:["should","must","would","could"],
answer:"should",alternates:[],
hint:"'Should have + past participle' expresses criticism or regret about something not done in the past."},

// ── FILL IN THE BLANK ─────────────────────────────────────────────────────────
{id:"fill_001",type:"fill",topic:"prepositions_time",
question:"I've been waiting for this opportunity _____ years.",
answer:"for",alternates:[],
hint:"Use 'for' with a period of time (years, months, hours). Use 'since' with a point in time."},

{id:"fill_002",type:"fill",topic:"phrasal_verbs",
question:"Could you please fill _____ this application form and return it by Friday?",
answer:"in",alternates:["out"],
hint:"Both 'fill in' and 'fill out' mean to complete a form. Both are correct."},

{id:"fill_003",type:"fill",topic:"verb_patterns_gerund",
question:"She suggested _____ (go) for a walk along the river.",
answer:"going",alternates:[],
hint:"'Suggest' is followed by a gerund (-ing), never a to-infinitive."},

{id:"fill_004",type:"fill",topic:"conjunctions",
question:"The weather was terrible. _____, we decided to go ahead with the outdoor event.",
answer:"Nevertheless",alternates:["However","Nonetheless"],
hint:"A contrast connector is needed to show the decision was made despite the bad weather."},

{id:"fill_005",type:"fill",topic:"prepositional_adjectives",
question:"She is extremely good _____ dealing with difficult customers.",
answer:"at",alternates:[],
hint:"The fixed pattern is 'good at (doing) something'. Compare: 'interested in', 'responsible for'."},

{id:"fill_006",type:"fill",topic:"collocations",
question:"Could you do me a _____? I need someone to look after my cat this weekend.",
answer:"favour",alternates:["favor"],
hint:"'Do someone a favour' is the fixed collocation for helping someone out."},

{id:"fill_007",type:"fill",topic:"prepositions_time",
question:"She has been studying medicine _____ she left school at eighteen.",
answer:"since",alternates:[],
hint:"Use 'since' with a specific point in time ('she left school' = a point, not a period)."},

{id:"fill_008",type:"fill",topic:"phrasal_verbs",
question:"The flight to Barcelona took _____ two hours late due to a technical fault.",
answer:"off",alternates:[],
hint:"'Take off' means for an aircraft to leave the ground."},

{id:"fill_009",type:"fill",topic:"conjunctions",
question:"You won't pass the driving test _____ you practise parallel parking.",
answer:"unless",alternates:[],
hint:"'Unless' = 'if not'. The only way to pass is to practise."},

{id:"fill_010",type:"fill",topic:"verb_patterns_gerund",
question:"I look forward _____ hearing from you soon.",
answer:"to",alternates:[],
hint:"'Look forward to' ends in a preposition 'to', so it's followed by a gerund. Do not add another 'to'."},

{id:"fill_011",type:"fill",topic:"prepositional_verbs",
question:"The police accused him _____ breaking into the warehouse.",
answer:"of",alternates:[],
hint:"The fixed pattern is 'accuse someone of (doing) something'."},

{id:"fill_012",type:"fill",topic:"collocations",
question:"I'm afraid she has made a serious _____ in her calculations.",
answer:"mistake",alternates:["error"],
hint:"'Make a mistake' is the standard collocation — never 'do a mistake'."},

{id:"fill_013",type:"fill",topic:"phrasal_verbs",
question:"He gave _____ his job to spend more time with his young family.",
answer:"up",alternates:[],
hint:"'Give up' = to quit or stop doing something (a job, a habit)."},

{id:"fill_014",type:"fill",topic:"prepositions_place",
question:"The supermarket is _____ the post office and the bank on the high street.",
answer:"between",alternates:[],
hint:"'Between' is used when something is in the middle of two specific things. 'Among' is for more than two."},

{id:"fill_015",type:"fill",topic:"verb_patterns_gerund",
question:"I can't stand _____ (wait) in queues — it drives me absolutely mad.",
answer:"waiting",alternates:[],
hint:"'Can't stand' is always followed by a gerund (-ing form)."},

{id:"fill_016",type:"fill",topic:"phrasal_verbs",
question:"I ran _____ my old flatmate from university while shopping.",
answer:"into",alternates:[],
hint:"'Run into someone' = to meet someone unexpectedly."},

{id:"fill_017",type:"fill",topic:"prepositional_adjectives",
question:"Are you really _____ of spiders? They're completely harmless!",
answer:"afraid",alternates:["scared","frightened","terrified"],
hint:"These adjectives all take 'of': afraid of, scared of, frightened of, terrified of."},

{id:"fill_018",type:"fill",topic:"collocations",
question:"You need to make _____ your mind before the deadline tomorrow.",
answer:"up",alternates:[],
hint:"'Make up your mind' is a fixed expression meaning to make a decision."},

{id:"fill_019",type:"fill",topic:"prepositions_time",
question:"The new safety regulations will come into force _____ the 1st of June.",
answer:"on",alternates:[],
hint:"Use 'on' with specific dates."},

{id:"fill_020",type:"fill",topic:"conjunctions",
question:"She wore a heavy coat _____ it was a warm summer evening.",
answer:"even though",alternates:["although","though"],
hint:"'Even though', 'although', and 'though' all introduce a contrast clause."},

// ── WORD FORMATION ────────────────────────────────────────────────────────────
{id:"wf_001",type:"word_form",topic:"word_building",
question:"Her [happy] at winning the award was obvious to everyone in the room.",
answer:"happiness",alternates:[],
hint:"Add '-ness' to 'happy' — spelling change: y → i: happiness."},

{id:"wf_002",type:"word_form",topic:"word_building",
question:"The government has made an important [decide] regarding public transport.",
answer:"decision",alternates:[],
hint:"The noun form of 'decide' is 'decision'."},

{id:"wf_003",type:"word_form",topic:"word_building",
question:"He showed remarkable [patient] while waiting for the test results.",
answer:"patience",alternates:[],
hint:"The noun form of the adjective 'patient' is 'patience'."},

{id:"wf_004",type:"word_form",topic:"word_building",
question:"The assembly instructions were completely [clear] — nobody knew what to do.",
answer:"unclear",alternates:[],
hint:"The negative prefix 'un-' means 'not'. 'Unclear' = not clear."},

{id:"wf_005",type:"word_form",topic:"word_building",
question:"She gave a [power] speech that moved the entire audience to tears.",
answer:"powerful",alternates:[],
hint:"Add the suffix '-ful' to the noun 'power' to form an adjective."},

{id:"wf_006",type:"word_form",topic:"word_building",
question:"The project was a great [succeed] — we exceeded all our targets.",
answer:"success",alternates:[],
hint:"The noun form of the verb 'succeed' is 'success'."},

{id:"wf_007",type:"word_form",topic:"word_building",
question:"He acted very [responsible] — he left without telling anyone where he was going.",
answer:"irresponsibly",alternates:[],
hint:"Prefix 'ir-' + 'responsible' + '-ly' for the adverb: irresponsibly."},

{id:"wf_008",type:"word_form",topic:"word_building",
question:"The charity works to reduce [employ] among young people in rural areas.",
answer:"unemployment",alternates:[],
hint:"Prefix 'un-' + 'employ' + suffix '-ment' → unemployment."},

{id:"wf_009",type:"word_form",topic:"word_building",
question:"Watching the sunrise from the summit was a truly [forget] experience.",
answer:"unforgettable",alternates:[],
hint:"'Un-' + 'forget' + '-table' → unforgettable. Note the double 't'."},

{id:"wf_010",type:"word_form",topic:"word_building",
question:"The museum offers an [educate] programme designed for school children.",
answer:"educational",alternates:[],
hint:"The adjective form of 'educate/education' is 'educational'."},

{id:"wf_011",type:"word_form",topic:"word_building",
question:"Could you provide some [explain] for your absence yesterday afternoon?",
answer:"explanation",alternates:[],
hint:"The noun form of 'explain' is 'explanation'."},

{id:"wf_012",type:"word_form",topic:"word_building",
question:"My son is applying for Swiss [nation] after living there for ten years.",
answer:"nationality",alternates:[],
hint:"'Nation' + '-ality' → nationality."},

{id:"wf_013",type:"word_form",topic:"word_building",
question:"The [friend] between the two rivals surprised everyone who knew them.",
answer:"friendship",alternates:[],
hint:"Add '-ship' to 'friend' to form the noun 'friendship'."},

{id:"wf_014",type:"word_form",topic:"word_building",
question:"She is well known for her [create] approach to solving complex problems.",
answer:"creative",alternates:[],
hint:"The adjective form of 'create/creativity' is 'creative'."},

{id:"wf_015",type:"word_form",topic:"word_building",
question:"There is a strong [relate] between diet and long-term health outcomes.",
answer:"relationship",alternates:["relation"],
hint:"The noun form of 'relate' is 'relation' or 'relationship'. 'Relationship' is more natural here."},

// ── KEY WORD TRANSFORMATION ───────────────────────────────────────────────────
{id:"tr_001",type:"transform",topic:"passive",
question:"Someone stole my bicycle last night.\nKEY WORD: STOLEN",
prefix:"My bicycle",suffix:"last night.",gapAnswer:"was stolen",gapAlternates:[],
answer:"My bicycle was stolen last night.",alternates:[],
hint:"Passive voice: subject + was/were + past participle. The doer ('someone') is dropped."},

{id:"tr_002",type:"transform",topic:"reported_speech",
question:"\"I will call you tomorrow,\" she said.\nKEY WORD: WOULD",
prefix:"She said she",suffix:"the next day.",gapAnswer:"would call me",gapAlternates:["would call you"],
answer:"She said she would call me the next day.",alternates:["She said that she would call me the next day.","She said she would call me tomorrow."],
hint:"In reported speech, 'will' → 'would'. Time expressions may shift: tomorrow → the next day."},

{id:"tr_003",type:"transform",topic:"present_perfect_vs_past_simple",
question:"This is the first time I've eaten sushi.\nKEY WORD: NEVER",
prefix:"I",suffix:"sushi before.",gapAnswer:"have never eaten",gapAlternates:["'ve never eaten","have never had"],
answer:"I have never eaten sushi before.",alternates:["I've never eaten sushi before.","I have never eaten sushi."],
hint:"'This is the first time I've done X' = 'I have never done X before'."},

{id:"tr_004",type:"transform",topic:"conditionals",
question:"I don't have a car, so I can't drive to work.\nKEY WORD: IF",
prefix:"",suffix:"I could drive to work.",gapAnswer:"If I had a car,",gapAlternates:["If I had a car"],
answer:"If I had a car, I could drive to work.",alternates:["If I had a car, I would drive to work."],
hint:"Conditional type 2: 'If + past simple, would/could + bare infinitive'."},

{id:"tr_005",type:"transform",topic:"comparative_superlative",
question:"No other mountain in Europe is as high as Mont Blanc.\nKEY WORD: HIGHEST",
prefix:"Mont Blanc is",suffix:"mountain in Europe.",gapAnswer:"the highest",gapAlternates:[],
answer:"Mont Blanc is the highest mountain in Europe.",alternates:[],
hint:"'No other X is as [adj] as Y' can be rewritten as 'Y is the most [adj] X'."},

{id:"tr_006",type:"transform",topic:"modal_verbs",
question:"It's not necessary for you to attend the meeting.\nKEY WORD: NEED",
prefix:"You",suffix:"the meeting.",gapAnswer:"needn't attend",gapAlternates:["don't need to attend","need not attend"],
answer:"You needn't attend the meeting.",alternates:["You don't need to attend the meeting.","You need not attend the meeting."],
hint:"'Don't need to' and 'needn't' both express lack of obligation."},

{id:"tr_007",type:"transform",topic:"passive",
question:"They are going to demolish the old factory next month.\nKEY WORD: DEMOLISHED",
prefix:"The old factory is",suffix:"next month.",gapAnswer:"going to be demolished",gapAlternates:[],
answer:"The old factory is going to be demolished next month.",alternates:[],
hint:"Future passive with 'going to': is/are going to be + past participle."},

{id:"tr_008",type:"transform",topic:"conjunctions",
question:"Although she was exhausted, she kept on working.\nKEY WORD: DESPITE",
prefix:"",suffix:"she kept on working.",gapAnswer:"Despite being exhausted,",gapAlternates:["Despite her exhaustion,","Despite being exhausted"],
answer:"Despite being exhausted, she kept on working.",alternates:["Despite her exhaustion, she kept on working."],
hint:"'Although + clause' → 'Despite + noun/gerund'. No subject needed after 'despite'."},

{id:"tr_009",type:"transform",topic:"conditionals",
question:"We didn't set off early, so we missed the ferry.\nKEY WORD: HAD",
prefix:"If we",suffix:"we wouldn't have missed the ferry.",gapAnswer:"had set off early,",gapAlternates:["had set off early"],
answer:"If we had set off early, we wouldn't have missed the ferry.",alternates:["Had we set off early, we wouldn't have missed the ferry."],
hint:"Conditional type 3: 'If + past perfect, would have + past participle'."},

{id:"tr_010",type:"transform",topic:"too_enough",
question:"The coffee is so hot that I can't drink it.\nKEY WORD: TOO",
prefix:"The coffee is",suffix:"to drink.",gapAnswer:"too hot",gapAlternates:["too hot for me"],
answer:"The coffee is too hot to drink.",alternates:["The coffee is too hot for me to drink."],
hint:"'So + adj + that + cannot' → 'too + adj + to + infinitive'."},

{id:"tr_011",type:"transform",topic:"present_perfect_continuous",
question:"She started learning Japanese three years ago and she still studies it.\nKEY WORD: FOR",
prefix:"She",suffix:"three years.",gapAnswer:"has been learning Japanese for",gapAlternates:["has been studying Japanese for"],
answer:"She has been learning Japanese for three years.",alternates:["She has been studying Japanese for three years."],
hint:"Present perfect continuous + 'for' describes an action that started in the past and continues now."},

{id:"tr_012",type:"transform",topic:"reported_speech",
question:"\"Don't touch the exhibits,\" the guard told us.\nKEY WORD: NOT",
prefix:"The guard told us",suffix:"the exhibits.",gapAnswer:"not to touch",gapAlternates:[],
answer:"The guard told us not to touch the exhibits.",alternates:[],
hint:"Reported negative imperative: told + object + not + to + bare infinitive."},

{id:"tr_013",type:"transform",topic:"modal_verbs",
question:"I'm sure he didn't take the money — it's simply impossible.\nKEY WORD: HAVE",
prefix:"He",suffix:"the money.",gapAnswer:"can't have taken",gapAlternates:["cannot have taken"],
answer:"He can't have taken the money.",alternates:[],
hint:"'Can't have + past participle' expresses near-certainty that something didn't happen in the past."},

{id:"tr_014",type:"transform",topic:"conjunctions",
question:"She earns very little money. However, she is very happy.\nKEY WORD: ALTHOUGH",
prefix:"",suffix:"very little money, she is very happy.",gapAnswer:"Although she earns",gapAlternates:["Although she earns"],
answer:"Although she earns very little money, she is very happy.",alternates:["She is very happy although she earns very little money."],
hint:"'Although + clause, clause' expresses contrast — the two clauses can swap positions."},

{id:"tr_015",type:"transform",topic:"verb_patterns_gerund_infinitive",
question:"It wasn't necessary for him to apologise, but he did anyway.\nKEY WORD: HAVE",
prefix:"He",suffix:"apologise, but he did anyway.",gapAnswer:"didn't have to",gapAlternates:[],
answer:"He didn't have to apologise, but he did anyway.",alternates:[],
hint:"'It wasn't necessary for someone to do X' = 'Someone didn't have to do X'."},

// ── TRUE / FALSE / NOT MENTIONED ──────────────────────────────────────────────
// Passage A
{id:"tf_001",type:"tf",topic:"reading_comprehension",
passage:"Remote working, once considered a perk reserved for a lucky few, has become standard practice for millions of employees worldwide. Research from Stanford University suggests that remote workers are 13% more productive than their office-based counterparts. However, critics point out that the long-term effects on company culture and team cohesion remain unclear. A 2023 survey found that 67% of managers believed remote employees were harder to evaluate fairly during performance reviews. Despite this, the majority of workers who have experienced remote work report they would not want to return to a traditional office environment full-time.",
question:"According to the passage, remote working has become widespread for many employees.",
answer:"True",alternates:[],
hint:"The passage states remote working 'has become standard practice for millions of employees worldwide'."},

{id:"tf_002",type:"tf",topic:"reading_comprehension",
passage:"Remote working, once considered a perk reserved for a lucky few, has become standard practice for millions of employees worldwide. Research from Stanford University suggests that remote workers are 13% more productive than their office-based counterparts. However, critics point out that the long-term effects on company culture and team cohesion remain unclear. A 2023 survey found that 67% of managers believed remote employees were harder to evaluate fairly during performance reviews. Despite this, the majority of workers who have experienced remote work report they would not want to return to a traditional office environment full-time.",
question:"Stanford University found remote workers produced exactly twice as much as office workers.",
answer:"False",alternates:[],
hint:"The research found 13% higher productivity, not twice as much."},

{id:"tf_003",type:"tf",topic:"reading_comprehension",
passage:"Remote working, once considered a perk reserved for a lucky few, has become standard practice for millions of employees worldwide. Research from Stanford University suggests that remote workers are 13% more productive than their office-based counterparts. However, critics point out that the long-term effects on company culture and team cohesion remain unclear. A 2023 survey found that 67% of managers believed remote employees were harder to evaluate fairly during performance reviews. Despite this, the majority of workers who have experienced remote work report they would not want to return to a traditional office environment full-time.",
question:"The survey showed that most managers were strongly in favour of making remote work permanent.",
answer:"Not Mentioned",alternates:[],
hint:"The survey mentions difficulty in evaluation, but does not reveal whether managers favour or oppose remote working."},

{id:"tf_004",type:"tf",topic:"reading_comprehension",
passage:"Remote working, once considered a perk reserved for a lucky few, has become standard practice for millions of employees worldwide. Research from Stanford University suggests that remote workers are 13% more productive than their office-based counterparts. However, critics point out that the long-term effects on company culture and team cohesion remain unclear. A 2023 survey found that 67% of managers believed remote employees were harder to evaluate fairly during performance reviews. Despite this, the majority of workers who have experienced remote work report they would not want to return to a traditional office environment full-time.",
question:"Most employees who have tried remote work prefer to return to the office full-time.",
answer:"False",alternates:[],
hint:"The passage says the majority 'would not want to return to a traditional office environment full-time'."},

{id:"tf_005",type:"tf",topic:"reading_comprehension",
passage:"Remote working, once considered a perk reserved for a lucky few, has become standard practice for millions of employees worldwide. Research from Stanford University suggests that remote workers are 13% more productive than their office-based counterparts. However, critics point out that the long-term effects on company culture and team cohesion remain unclear. A 2023 survey found that 67% of managers believed remote employees were harder to evaluate fairly during performance reviews. Despite this, the majority of workers who have experienced remote work report they would not want to return to a traditional office environment full-time.",
question:"Critics are concerned about the long-term impact of remote working on team dynamics.",
answer:"True",alternates:[],
hint:"Critics point out that 'the long-term effects on company culture and team cohesion remain unclear'."},

// Passage B
{id:"tf_006",type:"tf",topic:"reading_comprehension",
passage:"Social media platforms are facing increasing pressure from governments and health organisations to address their mental health impact on teenagers. A report by the UK Children's Commissioner found that children as young as eight are regularly using platforms designed for adults. While some studies link heavy social media use to higher rates of anxiety and depression among adolescents, other researchers argue the relationship is far more complex and that social media can also provide valuable social support. Several major platforms have introduced screen time limits and age verification features, though critics argue these measures are largely ineffective.",
question:"Some children younger than thirteen regularly use social media platforms intended for adults.",
answer:"True",alternates:[],
hint:"The passage states 'children as young as eight are regularly using platforms designed for adults'."},

{id:"tf_007",type:"tf",topic:"reading_comprehension",
passage:"Social media platforms are facing increasing pressure from governments and health organisations to address their mental health impact on teenagers. A report by the UK Children's Commissioner found that children as young as eight are regularly using platforms designed for adults. While some studies link heavy social media use to higher rates of anxiety and depression among adolescents, other researchers argue the relationship is far more complex and that social media can also provide valuable social support. Several major platforms have introduced screen time limits and age verification features, though critics argue these measures are largely ineffective.",
question:"All researchers agree that social media has a harmful effect on young people's mental health.",
answer:"False",alternates:[],
hint:"Other researchers argue the relationship is 'far more complex' and that social media can provide 'valuable social support'."},

{id:"tf_008",type:"tf",topic:"reading_comprehension",
passage:"Social media platforms are facing increasing pressure from governments and health organisations to address their mental health impact on teenagers. A report by the UK Children's Commissioner found that children as young as eight are regularly using platforms designed for adults. While some studies link heavy social media use to higher rates of anxiety and depression among adolescents, other researchers argue the relationship is far more complex and that social media can also provide valuable social support. Several major platforms have introduced screen time limits and age verification features, though critics argue these measures are largely ineffective.",
question:"The UK government has banned children under thirteen from using social media.",
answer:"Not Mentioned",alternates:[],
hint:"The passage mentions government pressure but says nothing about a specific ban being introduced."},

{id:"tf_009",type:"tf",topic:"reading_comprehension",
passage:"Social media platforms are facing increasing pressure from governments and health organisations to address their mental health impact on teenagers. A report by the UK Children's Commissioner found that children as young as eight are regularly using platforms designed for adults. While some studies link heavy social media use to higher rates of anxiety and depression among adolescents, other researchers argue the relationship is far more complex and that social media can also provide valuable social support. Several major platforms have introduced screen time limits and age verification features, though critics argue these measures are largely ineffective.",
question:"Several social media companies have taken steps to limit how long users spend on their platforms.",
answer:"True",alternates:[],
hint:"The passage says 'several major platforms have introduced screen time limits'."},

{id:"tf_010",type:"tf",topic:"reading_comprehension",
passage:"Social media platforms are facing increasing pressure from governments and health organisations to address their mental health impact on teenagers. A report by the UK Children's Commissioner found that children as young as eight are regularly using platforms designed for adults. While some studies link heavy social media use to higher rates of anxiety and depression among adolescents, other researchers argue the relationship is far more complex and that social media can also provide valuable social support. Several major platforms have introduced screen time limits and age verification features, though critics argue these measures are largely ineffective.",
question:"Critics believe the protective measures introduced by platforms are not working well enough.",
answer:"True",alternates:[],
hint:"The passage states 'critics argue these measures are largely ineffective'."},

// Passage C
{id:"tf_011",type:"tf",topic:"reading_comprehension",
passage:"The concept of 'slow travel' is gaining popularity among environmentally conscious tourists. Unlike traditional package holidays, slow travel encourages visitors to spend more time in fewer destinations, using low-carbon transport such as trains and bicycles. Advocates argue this approach not only reduces the environmental impact of tourism but also allows travellers to develop a deeper connection with local cultures. However, slow travel is not accessible to everyone — it typically requires more time and money than a standard holiday, making it largely the preserve of wealthy, flexible workers. Switzerland has positioned itself as a leader in sustainable tourism, with its extensive rail network and emphasis on nature-based activities.",
question:"Slow travel involves visiting as many destinations as possible in the time available.",
answer:"False",alternates:[],
hint:"Slow travel encourages visitors to 'spend more time in fewer destinations'."},

{id:"tf_012",type:"tf",topic:"reading_comprehension",
passage:"The concept of 'slow travel' is gaining popularity among environmentally conscious tourists. Unlike traditional package holidays, slow travel encourages visitors to spend more time in fewer destinations, using low-carbon transport such as trains and bicycles. Advocates argue this approach not only reduces the environmental impact of tourism but also allows travellers to develop a deeper connection with local cultures. However, slow travel is not accessible to everyone — it typically requires more time and money than a standard holiday, making it largely the preserve of wealthy, flexible workers. Switzerland has positioned itself as a leader in sustainable tourism, with its extensive rail network and emphasis on nature-based activities.",
question:"One benefit of slow travel, according to its supporters, is a greater understanding of local culture.",
answer:"True",alternates:[],
hint:"Advocates say it 'allows travellers to develop a deeper connection with local cultures'."},

{id:"tf_013",type:"tf",topic:"reading_comprehension",
passage:"The concept of 'slow travel' is gaining popularity among environmentally conscious tourists. Unlike traditional package holidays, slow travel encourages visitors to spend more time in fewer destinations, using low-carbon transport such as trains and bicycles. Advocates argue this approach not only reduces the environmental impact of tourism but also allows travellers to develop a deeper connection with local cultures. However, slow travel is not accessible to everyone — it typically requires more time and money than a standard holiday, making it largely the preserve of wealthy, flexible workers. Switzerland has positioned itself as a leader in sustainable tourism, with its extensive rail network and emphasis on nature-based activities.",
question:"Slow travel is equally available to all types of traveller regardless of income.",
answer:"False",alternates:[],
hint:"The passage says it is 'largely the preserve of wealthy, flexible workers', so not equally available."},

{id:"tf_014",type:"tf",topic:"reading_comprehension",
passage:"The concept of 'slow travel' is gaining popularity among environmentally conscious tourists. Unlike traditional package holidays, slow travel encourages visitors to spend more time in fewer destinations, using low-carbon transport such as trains and bicycles. Advocates argue this approach not only reduces the environmental impact of tourism but also allows travellers to develop a deeper connection with local cultures. However, slow travel is not accessible to everyone — it typically requires more time and money than a standard holiday, making it largely the preserve of wealthy, flexible workers. Switzerland has positioned itself as a leader in sustainable tourism, with its extensive rail network and emphasis on nature-based activities.",
question:"Switzerland recently introduced new legislation to support sustainable tourism.",
answer:"Not Mentioned",alternates:[],
hint:"Switzerland's position is mentioned, but the passage says nothing about new legislation."},

{id:"tf_015",type:"tf",topic:"reading_comprehension",
passage:"The concept of 'slow travel' is gaining popularity among environmentally conscious tourists. Unlike traditional package holidays, slow travel encourages visitors to spend more time in fewer destinations, using low-carbon transport such as trains and bicycles. Advocates argue this approach not only reduces the environmental impact of tourism but also allows travellers to develop a deeper connection with local cultures. However, slow travel is not accessible to everyone — it typically requires more time and money than a standard holiday, making it largely the preserve of wealthy, flexible workers. Switzerland has positioned itself as a leader in sustainable tourism, with its extensive rail network and emphasis on nature-based activities.",
question:"Switzerland is considered a leading country for sustainable tourism.",
answer:"True",alternates:[],
hint:"The passage says Switzerland 'has positioned itself as a leader in sustainable tourism'."},

// ── ERROR CORRECTION ──────────────────────────────────────────────────────────
{id:"err_001",type:"error",topic:"verb_patterns_gerund",
question:"I'm really looking forward to meet you at the conference next week.",
answer:"meet",alternates:[],correction:"meeting",correctionAlternates:[],
hint:"'Look forward to' ends in the preposition 'to', so it must be followed by a gerund: 'looking forward to meeting'."},

{id:"err_002",type:"error",topic:"present_perfect_vs_past_simple",
question:"I have seen that film last Tuesday. It was really disappointing.",
answer:"have seen",alternates:[],correction:"saw",correctionAlternates:[],
hint:"'Last Tuesday' is a specific finished time reference, so use past simple: 'I saw that film last Tuesday'."},

{id:"err_003",type:"error",topic:"prepositions_time",
question:"She has been living in this city since three years.",
answer:"since",alternates:[],correction:"for",correctionAlternates:[],
hint:"Use 'for' with a period of time ('three years'). 'Since' goes with a point in time."},

{id:"err_004",type:"error",topic:"countable_uncountable",
question:"He gave me a very useful advise about how to prepare for the exam.",
answer:"advise",alternates:["a"],correction:"advice",correctionAlternates:[""],
hint:"'Advice' (noun, uncountable) cannot be preceded by 'a'. 'Advise' is a verb, not a noun."},

{id:"err_005",type:"error",topic:"adjectives_ed_ing",
question:"I was completely boring at the party — there was nobody interesting to talk to.",
answer:"boring",alternates:[],correction:"bored",correctionAlternates:[],
hint:"Use '-ed' adjectives to describe how a person feels: 'I was bored'. '-ing' describes the cause of the feeling."},

{id:"err_006",type:"error",topic:"conditionals",
question:"If I would have more free time, I'd take up painting as a hobby.",
answer:"would",alternates:["would have"],correction:"had",correctionAlternates:["had"],
hint:"In the if-clause of a type 2 conditional, use past simple — never 'would': 'If I had more free time...'"},

{id:"err_007",type:"error",topic:"relative_clauses",
question:"The restaurant which we had dinner last night was absolutely fantastic.",
answer:"which",alternates:[],correction:"where",correctionAlternates:[],
hint:"For places where an action occurs, use 'where': 'the restaurant where we had dinner'. Or add a preposition: 'at which'."},

{id:"err_008",type:"error",topic:"adverbs_vs_adjectives",
question:"She performed incredible well in the final round of the competition.",
answer:"incredible",alternates:[],correction:"incredibly",correctionAlternates:[],
hint:"An adverb is needed to modify another adverb ('well'). Use 'incredibly well', not 'incredible well'."},

{id:"err_009",type:"error",topic:"modal_verbs",
question:"Visitors mustn't to take photographs inside the museum.",
answer:"to",alternates:[],correction:"",correctionAlternates:["-","delete","remove","omit"],
hint:"After modal verbs (must, can, will, should, etc.), use the bare infinitive — no 'to'. The word should be deleted."},

{id:"err_010",type:"error",topic:"passive",
question:"The results were announced by publicly on the official website yesterday.",
answer:"by",alternates:[],correction:"",correctionAlternates:["-","delete","remove","omit"],
hint:"'Publicly' is an adverb — it does not need 'by'. The word should be deleted."},

{id:"err_011",type:"error",topic:"verb_patterns_gerund_infinitive",
question:"She stopped to smoke when her doctor explained the health risks.",
answer:"to smoke",alternates:[],correction:"smoking",correctionAlternates:[],
hint:"'Stop + gerund' = to quit a habit. 'Stop + infinitive' = to pause in order to do something else. She quit smoking."},

{id:"err_012",type:"error",topic:"articles",
question:"He is a best student in the class and always gets top marks.",
answer:"a",alternates:[],correction:"the",correctionAlternates:[],
hint:"Use the definite article 'the' before superlatives, not the indefinite 'a': 'He is the best student'."},

{id:"err_013",type:"error",topic:"reported_speech",
question:"She told me that she is working on an exciting new project.",
answer:"is working",alternates:["is"],correction:"was working",correctionAlternates:["was"],
hint:"In reported speech, present continuous ('is working') shifts back to past continuous ('was working')."},

{id:"err_014",type:"error",topic:"comparative_superlative",
question:"This year's exam results are more better than last year's by a significant margin.",
answer:"more",alternates:[],correction:"",correctionAlternates:["-","delete","remove","omit"],
hint:"'Better' is already the comparative form of 'good'. Never add 'more' to an irregular comparative — delete it."},

{id:"err_015",type:"error",topic:"phrasal_verbs",
question:"Could you look after this complaint while I'm away? It needs urgent attention.",
answer:"after",alternates:["look after"],correction:"into",correctionAlternates:["look into"],
hint:"'Look after' means to care for someone/something. To investigate a complaint, use 'look into' or 'deal with'."},
];
